### YamlMime:ManagedReference
items:
- uid: Speechly.Types.ContextOptions.ShallowFusionSettings
  commentId: T:Speechly.Types.ContextOptions.ShallowFusionSettings
  id: ContextOptions.ShallowFusionSettings
  parent: Speechly.Types
  children:
  - Speechly.Types.ContextOptions.ShallowFusionSettings.Vocabulary
  - Speechly.Types.ContextOptions.ShallowFusionSettings.Weight
  langs:
  - csharp
  - vb
  name: ContextOptions.ShallowFusionSettings
  nameWithType: ContextOptions.ShallowFusionSettings
  fullName: Speechly.Types.ContextOptions.ShallowFusionSettings
  type: Class
  source:
    remote:
      path: speechly-dotnet/Speechly/SpeechlyClient/Types.cs
      branch: main
      repo: git@github.com:speechly/speechly-unity-dotnet.git
    id: ShallowFusionSettings
    path: speechly-dotnet/Speechly/SpeechlyClient/Types.cs
    startLine: 201
  assemblies:
  - speechly-dotnet
  namespace: Speechly.Types
  summary: "\nIncrease or decrease the probability of recognizing the provided words\n"
  example: []
  syntax:
    content: 'public class ShallowFusionSettings : object'
    content.vb: >-
      Public Class ShallowFusionSettings
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Speechly.Types.ContextOptions.ShallowFusionSettings.Vocabulary
  commentId: F:Speechly.Types.ContextOptions.ShallowFusionSettings.Vocabulary
  id: Vocabulary
  parent: Speechly.Types.ContextOptions.ShallowFusionSettings
  langs:
  - csharp
  - vb
  name: Vocabulary
  nameWithType: ContextOptions.ShallowFusionSettings.Vocabulary
  fullName: Speechly.Types.ContextOptions.ShallowFusionSettings.Vocabulary
  type: Field
  source:
    remote:
      path: speechly-dotnet/Speechly/SpeechlyClient/Types.cs
      branch: main
      repo: git@github.com:speechly/speechly-unity-dotnet.git
    id: Vocabulary
    path: speechly-dotnet/Speechly/SpeechlyClient/Types.cs
    startLine: 210
  assemblies:
  - speechly-dotnet
  namespace: Speechly.Types
  example: []
  syntax:
    content: public string Vocabulary
    return:
      type: System.String
      description: "\nNewline-delimited words that specify the vocabulary for score biasing.\n"
    content.vb: Public Vocabulary As String
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Speechly.Types.ContextOptions.ShallowFusionSettings.Weight
  commentId: F:Speechly.Types.ContextOptions.ShallowFusionSettings.Weight
  id: Weight
  parent: Speechly.Types.ContextOptions.ShallowFusionSettings
  langs:
  - csharp
  - vb
  name: Weight
  nameWithType: ContextOptions.ShallowFusionSettings.Weight
  fullName: Speechly.Types.ContextOptions.ShallowFusionSettings.Weight
  type: Field
  source:
    remote:
      path: speechly-dotnet/Speechly/SpeechlyClient/Types.cs
      branch: main
      repo: git@github.com:speechly/speechly-unity-dotnet.git
    id: Weight
    path: speechly-dotnet/Speechly/SpeechlyClient/Types.cs
    startLine: 219
  assemblies:
  - speechly-dotnet
  namespace: Speechly.Types
  example: []
  syntax:
    content: public float Weight
    return:
      type: System.Single
      description: "\nBiasing weight. Positive values increase the probability of recognition, negative values decrease it.\n"
    content.vb: Public Weight As Single
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Speechly.Types
  commentId: N:Speechly.Types
  name: Speechly.Types
  nameWithType: Speechly.Types
  fullName: Speechly.Types
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Single
  isExternal: true
  name: Single
  nameWithType: Single
  fullName: System.Single
